### ISSUE TITLE
Use latest Go version

### ISSUE THREAD

**Issue by yagikota** [buffrr/letsdane#29]
Hi @buffrr 
Thanks for awesome library!

If we are going to continue to develop this library, we'll have to increase Go version at some point.
Do you have plan to use latest Go version 1.21.

**Comment by yagikota** [comment]
@buffrr 

Thanks for your reply.

So can I create PR to use Go1.21?

**Comment by buffrr** [comment]
Yes, go ahead!

**Comment by yagikota** [comment]
OK!
If we could update Go version from 1.5 to 1.21, I'll work on the following PR.
https://github.com/buffrr/letsdane/pull/28
