### ISSUE TITLE
Discord doesn't connect even with -skip-icann

### ISSUE THREAD

**Issue by rithvikvibhu** [buffrr/letsdane#5]
I use letsdane on android (well, the proxy runs on a raspi). All apps and browsers work fine. DANE for Handshake names also works. But the Discord app doesn't. It's always on connecting. Could be a websocket thing or some kind of pinning, but I thought `-skip-icann` doesn't modify anything.

Will try to debug this more, just wanted to post it here first if you had any ideas.

**Comment by buffrr** [comment]
even if you don't use `-skip-icann` it should work. letsdane only modifies requests that have a TLSA record otherwise it just forwards the request. Do you see any errors in the logs? you can also use `-verbose` to see if there is anything else from discord.

**Comment by rithvikvibhu** [comment]
Sorry, turns out it was Resolvr (https://resolvr.info) not responding properly. Which is weird because that's the first thing I tested with dig and it worked.

Anyway, discord worked fine when letsdane used hnsd and hsd.
