### ISSUE TITLE
Proposal: Set listening IP_Addr and Port

### ISSUE THREAD

**Issue by micadeyeye** [buffrr/letsdane#6]
The following is your instruction to run Letsdane:
---------------------
./letsdane

    Add Let's DANE proxy to your web browser 127.0.0.1:8080
-----------------------
T
If you could you make it possible to set the IP_Addr and Port as (additional) arguments at which the service runs, that would be lovely.

Thank you for this interesting project.

**Comment by buffrr** [comment]
You can already do this using the `-addr` option which takes `ip:port`. For example, to listen on `127.0.0.1` with port `8585`:

```
letsdane -addr 127.0.0.1:8585
```

You can use `letsdane -help` to see available command line options.
